name: Create draft release

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

jobs:
  create-branch-release:
    runs-on: windows-2022
    steps:
    - name: Create branch release
      run: >
        gh release create v2.0.0-${{ github.head_ref  }}
          --draft --prerelease
          --repo ZADNE/RealEngine
          --target ${{ github.head_ref }}
          --title RealEngine v2.0.0-${{ github.head_ref  }}
      env:
        GH_TOKEN: ${{ github.token }}