name: Formatting check

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
    - name: Clone Real
      uses: actions/checkout@v4
      with:
        repository: ZADNE/Real
        path: Real

    - name: Clone RealEngine
      uses: actions/checkout@v4
      with:
        repository: ZADNE/RealEngine
        ref: ${{github.ref}}
        path: Real/RealEngine
        clean: false

    - name: Check formatting
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '17'
        check-path: 'Real/RealEngine/src'
