name: Formatting

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  formatting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
    - name: Real formatting check
      uses: ZADNE/RealFormatting@v0.1
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: src
